export const INTERESTS = [
  { id: "coffee", name: "Coffee", emoji: "☕" },
  { id: "travel", name: "Travel", emoji: "✈️" },
  { id: "music", name: "Music", emoji: "🎵" },
  { id: "food", name: "Food", emoji: "🍕" },
  { id: "fitness", name: "Fitness", emoji: "💪" },
  { id: "art", name: "Art", emoji: "🎨" },
  { id: "photography", name: "Photography", emoji: "📸" },
  { id: "reading", name: "Reading", emoji: "📚" },
  { id: "gaming", name: "Gaming", emoji: "🎮" },
  { id: "movies", name: "Movies", emoji: "🎬" },
  { id: "tech", name: "Technology", emoji: "💻" },
  { id: "nature", name: "Nature", emoji: "🌿" },
  { id: "pets", name: "Pets", emoji: "🐶" },
  { id: "cooking", name: "Cooking", emoji: "👨‍🍳" },
  { id: "fashion", name: "Fashion", emoji: "👗" },
  { id: "sports", name: "Sports", emoji: "⚽" },
  { id: "yoga", name: "Yoga", emoji: "🧘" },
  { id: "writing", name: "Writing", emoji: "✍️" },
];
